### ISSUE TITLE
Tfod Mobilenet v2 fails to convert tp onnx

### ISSUE THREAD

**Issue by thiemoToadi** [pskiran1/TensorRT-support-for-Tensorflow-2-Object-Detection-Models#4]
When trying to convert the tfod mobilenet v2 320x320 coco model I run into the following error: 
`Traceback (most recent call last):
  File "create_onnx.py", line 712, in <module>
    main(args)
  File "create_onnx.py", line 690, in main
    effdet_gs.update_preprocessor(args.batch_size)
  File "create_onnx.py", line 261, in update_preprocessor
    cast_node = [node for node in self.graph.nodes if node.op == "Tile" and cast_name in node.name][0]
IndexError: list index out of range
`

info:
python3.8
libraries installed from requirements.txt

**Comment by ayadgithub** [comment]
> When trying to convert the tfod mobilenet v2 320x320 coco model I run into the following error: `Traceback (most recent call last): File "create_onnx.py", line 712, in <module> main(args) File "create_onnx.py", line 690, in main effdet_gs.update_preprocessor(args.batch_size) File "create_onnx.py", line 261, in update_preprocessor cast_node = [node for node in self.graph.nodes if node.op == "Tile" and cast_name in node.name][0] IndexError: list index out of range `
> 
> info: python3.8 libraries installed from requirements.txt

Hi @thiemoToadi ,I, facing the same issue ,did you manage to resolve it ?

**Comment by 4ff4n** [comment]
hello i am facing the same issue. Has someone managed to fix it out?
please help!

**Comment by RyanK916** [comment]
Same issue here.  Any resolution yet?

**Comment by 4ff4n** [comment]
Hi @RyanK916 please re-export your model with float_image_tensor as it's input type and then try the conversation. 
Best!

**Comment by RyanK916** [comment]
@4ff4n Thanks for the reply.  I did use the --input_type float_image_tensor flag for exporter_main_v2.py in my original attempt.  I tried it again just to verify.  Here is the tail end of the output:

`WARNING:tf2onnx.onnx_opset.nn:Node StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/FeatureMaps/layer_19_2_Conv2d_5_3x3_s2_128_batchnorm/FusedBatchNormV3 of type FusedBatchNormV3 has is_training set to true, which is not supperted. Please re-save the model with training set to false.
INFO:tf2onnx.optimizer:Optimizing ONNX model
INFO:tf2onnx.optimizer:After optimization: BatchNormalization -53 (60->7), Cast -31 (94->63), Const -478 (686->208), Identity -67 (67->0), Mul -2 (35->33), ReduceSum -1 (2->1), Reshape +1 (24->25), Shape -2 (17->15), Slice -1 (25->24), Squeeze -2 (32->30), Sub -1 (21->20), Transpose -253 (274->21), Unsqueeze -8 (41->33)
INFO:ModelHelper:TF2ONNX graph created successfully
INFO:ModelHelper:ONNX graph input shape: [1, 300, 300, 3] [NCHW format set]
INFO:ModelHelper:Found Conv node 'StatefulPartitionedCall/ssd_mobile_net_v2keras_feature_extractor/model/Conv1/Conv2D' as stem entry
Traceback (most recent call last):
  File "create_onnx.py", line 688, in <module>
    main(args)
  File "create_onnx.py", line 666, in main
    effdet_gs.update_preprocessor(args.batch_size)
  File "create_onnx.py", line 251, in update_preprocessor
    cast_node = [node for node in self.graph.nodes if node.op == "Tile" and cast_name in node.name][0]
IndexError: list index out of range
` 

The pipeline is using "ssd_mobilenet_v2_keras" as the feature extractor type.

Thanks in advance for your continued help!

**Comment by RyanK916** [comment]
Another note on the above issue: my model is a retrained version of SSD MobileNet v2 where the number of classes has been changed to 1 and the aspect ratios have been changed from the original set.  Here is my pipeline.config:
`model {
  ssd {
    num_classes: 1
    image_resizer {
      fixed_shape_resizer {
        height: 300
        width: 300
      }
    }
    feature_extractor {
      type: "ssd_mobilenet_v2_keras"
      depth_multiplier: 1.0
      min_depth: 16
      conv_hyperparams {
        regularizer {
          l2_regularizer {
            weight: 4e-05
          }
        }
        initializer {
          truncated_normal_initializer {
            mean: 0.0
            stddev: 0.03
          }
        }
        activation: RELU_6
        batch_norm {
          decay: 0.97
          center: true
          scale: true
          epsilon: 0.001
          train: true
        }
      }
      override_base_feature_extractor_hyperparams: true
    }
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
        use_matmul_gather: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    box_predictor {
      convolutional_box_predictor {
        conv_hyperparams {
          regularizer {
            l2_regularizer {
              weight: 4e-05
            }
          }
          initializer {
            random_normal_initializer {
              mean: 0.0
              stddev: 0.01
            }
          }
          activation: RELU_6
          batch_norm {
            decay: 0.97
            center: true
            scale: true
            epsilon: 0.001
            train: true
          }
        }
        min_depth: 0
        max_depth: 0
        num_layers_before_predictor: 0
        use_dropout: false
        dropout_keep_probability: 0.8
        kernel_size: 1
        box_code_size: 4
        apply_sigmoid_to_scores: false
        class_prediction_bias_init: -4.6
      }
    }
    anchor_generator {
      ssd_anchor_generator {
        num_layers: 6
        min_scale: 0.17
        max_scale: 0.7
        aspect_ratios: 1.0
      }
    }
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-08
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
    normalize_loss_by_num_matches: true
    loss {
      localization_loss {
        weighted_smooth_l1 {
          delta: 1.0
        }
      }
      classification_loss {
        weighted_sigmoid_focal {
          gamma: 2.0
          alpha: 0.75
        }
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    encode_background_as_zeros: true
    normalize_loc_loss_by_codesize: true
    inplace_batchnorm_update: true
    freeze_batchnorm: false
  }
}
train_config {
  batch_size: 64
  data_augmentation_options {
    random_horizontal_flip {
    }
  }
  data_augmentation_options {
    random_image_scale {
      min_scale_ratio: 0.5
      max_scale_ratio: 1.25
    }
  }
  data_augmentation_options {
    random_adjust_brightness {
    }
  }
  sync_replicas: true
  optimizer {
    momentum_optimizer {
      learning_rate {
        cosine_decay_learning_rate {
          learning_rate_base: 0.8
          total_steps: 50000
          warmup_learning_rate: 0.13333
          warmup_steps: 2000
        }
      }
      momentum_optimizer_value: 0.9
    }
    use_moving_average: false
  }
  fine_tune_checkpoint: "pretrained_models/ssd_mobilenet_v2_320x320_coco17_tpu-8/checkpoint/ckpt-0"
  num_steps: 100000
  startup_delay_steps: 0.0
  replicas_to_aggregate: 8
  max_number_of_boxes: 100
  unpad_groundtruth_tensors: false
  fine_tune_checkpoint_type: "detection"
  fine_tune_checkpoint_version: V2
}
train_input_reader {
  label_map_path: "data/label_map.txt"
  tf_record_input_reader {
    input_path: "data/wheels_train_dt_5.record"
  }
}
eval_config {
  metrics_set: "coco_detection_metrics"
  use_moving_averages: false
}
eval_input_reader {
  label_map_path: "data/label_map.txt"
  shuffle: false
  num_epochs: 1
  tf_record_input_reader {
    input_path: "data/wheels_val_dt_5.record"
  }
}
`

**Comment by 4ff4n** [comment]
@RyanK916 The script "create_onnx.py" under this repository is bit old please use the updated version of this script given below:

https://github.com/NVIDIA/TensorRT/blob/8.2.1/samples/python/tensorflow_object_detection_api/create_onnx.py

Best!

**Comment by 3ryand** [comment]
I have the same issue here, how did you manage to resolve it?

**Comment by r2ba7** [comment]
Same issue here ..

**Comment by pskiran1** [comment]
Hi,

We have [official repo](https://github.com/NVIDIA/TensorRT/tree/main/samples/python/tensorflow_object_detection_api) available now, please reach out here for the help.
This repo will be removed now and it was temporary.

Thank you.
