### ISSUE TITLE
finetuned SSD Mobilenet v2 FPNLite 320x320 is failed during build/inference

### ISSUE THREAD

**Issue by mezdahun** [pskiran1/TensorRT-support-for-Tensorflow-2-Object-Detection-Models#6]
Hi There,

first of all thank you for the repo! This is so far the only solution I could push my model until the step when I build it on my nVidia Jetson nano 4GB from an onnx file.

I followed everything step by step and 'build_engine.py' is even able to build a trt engine but when I tried to load the trt for inference (with trtexec benchmark) I get the following error (I have left the summary info in there too):

```
[11/26/2021-14:22:22] [I] === Model Options ===
[11/26/2021-14:22:22] [I] Format: *
[11/26/2021-14:22:22] [I] Model: 
[11/26/2021-14:22:22] [I] Output:
[11/26/2021-14:22:22] [I] === Build Options ===
[11/26/2021-14:22:22] [I] Max batch: 1
[11/26/2021-14:22:22] [I] Workspace: 8 MiB
[11/26/2021-14:22:22] [I] minTiming: 1
[11/26/2021-14:22:22] [I] avgTiming: 8
[11/26/2021-14:22:22] [I] Precision: FP32
[11/26/2021-14:22:22] [I] Calibration: 
[11/26/2021-14:22:22] [I] Refit: Disabled
[11/26/2021-14:22:22] [I] Sparsity: Disabled
[11/26/2021-14:22:22] [I] Safe mode: Disabled
[11/26/2021-14:22:22] [I] Restricted mode: Disabled
[11/26/2021-14:22:22] [I] Save engine: 
[11/26/2021-14:22:22] [I] Load engine: /home/nano/Downloads/floatmodel_withTROD.trt
[11/26/2021-14:22:22] [I] NVTX verbosity: 0
[11/26/2021-14:22:22] [I] Tactic sources: Using default tactic sources
[11/26/2021-14:22:22] [I] timingCacheMode: local
[11/26/2021-14:22:22] [I] timingCacheFile: 
[11/26/2021-14:22:22] [I] Input(s)s format: fp32:CHW
[11/26/2021-14:22:22] [I] Output(s)s format: fp32:CHW
[11/26/2021-14:22:22] [I] Input build shapes: model
[11/26/2021-14:22:22] [I] Input calibration shapes: model
[11/26/2021-14:22:22] [I] === System Options ===
[11/26/2021-14:22:22] [I] Device: 0
[11/26/2021-14:22:22] [I] DLACore: 
[11/26/2021-14:22:22] [I] Plugins:
[11/26/2021-14:22:22] [I] === Inference Options ===
[11/26/2021-14:22:22] [I] Batch: 1
[11/26/2021-14:22:22] [I] Input inference shapes: model
[11/26/2021-14:22:22] [I] Iterations: 100
[11/26/2021-14:22:22] [I] Duration: 3s (+ 200ms warm up)
[11/26/2021-14:22:22] [I] Sleep time: 0ms
[11/26/2021-14:22:22] [I] Streams: 1
[11/26/2021-14:22:22] [I] ExposeDMA: Disabled
[11/26/2021-14:22:22] [I] Data transfers: Disabled
[11/26/2021-14:22:22] [I] Spin-wait: Disabled
[11/26/2021-14:22:22] [I] Multithreading: Disabled
[11/26/2021-14:22:22] [I] CUDA Graph: Enabled
[11/26/2021-14:22:22] [I] Separate profiling: Disabled
[11/26/2021-14:22:22] [I] Time Deserialize: Disabled
[11/26/2021-14:22:22] [I] Time Refit: Disabled
[11/26/2021-14:22:22] [I] Skip inference: Disabled
[11/26/2021-14:22:22] [I] Inputs:
[11/26/2021-14:22:22] [I] === Reporting Options ===
[11/26/2021-14:22:22] [I] Verbose: Disabled
[11/26/2021-14:22:22] [I] Averages: 100 inferences
[11/26/2021-14:22:22] [I] Percentile: 99
[11/26/2021-14:22:22] [I] Dump refittable layers:Disabled
[11/26/2021-14:22:22] [I] Dump output: Disabled
[11/26/2021-14:22:22] [I] Profile: Disabled
[11/26/2021-14:22:22] [I] Export timing to JSON file: 
[11/26/2021-14:22:22] [I] Export output to JSON file: 
[11/26/2021-14:22:22] [I] Export profile to JSON file: 
[11/26/2021-14:22:22] [I] 
[11/26/2021-14:22:22] [I] === Device Information ===
[11/26/2021-14:22:22] [I] Selected Device: NVIDIA Tegra X1
[11/26/2021-14:22:22] [I] Compute Capability: 5.3
[11/26/2021-14:22:22] [I] SMs: 1
[11/26/2021-14:22:22] [I] Compute Clock Rate: 0.9216 GHz
[11/26/2021-14:22:22] [I] Device Global Memory: 3956 MiB
[11/26/2021-14:22:22] [I] Shared Memory per SM: 64 KiB
[11/26/2021-14:22:22] [I] Memory Bus Width: 64 bits (ECC disabled)
[11/26/2021-14:22:22] [I] Memory Clock Rate: 0.01275 GHz
[11/26/2021-14:22:22] [I] 
[11/26/2021-14:22:22] [I] TensorRT version: 8001
[11/26/2021-14:22:24] [I] [TRT] [MemUsageChange] Init CUDA: CPU +202, GPU +0, now: CPU 233, GPU 3211 (MiB)
[11/26/2021-14:22:24] [I] [TRT] Loaded engine size: 12 MB
[11/26/2021-14:22:24] [I] [TRT] [MemUsageSnapshot] deserializeCudaEngine begin: CPU 233 MiB, GPU 3211 MiB
[11/26/2021-14:22:25] [I] [TRT] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +158, GPU +160, now: CPU 392, GPU 3371 (MiB)
[11/26/2021-14:22:27] [I] [TRT] [MemUsageChange] Init cuDNN: CPU +241, GPU +239, now: CPU 633, GPU 3610 (MiB)
[11/26/2021-14:22:27] [I] [TRT] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 632, GPU 3610 (MiB)
[11/26/2021-14:22:27] [I] [TRT] [MemUsageSnapshot] deserializeCudaEngine end: CPU 632 MiB, GPU 3610 MiB
[11/26/2021-14:22:27] [I] Engine loaded in 4.44206 sec.
[11/26/2021-14:22:27] [I] [TRT] [MemUsageSnapshot] ExecutionContext creation begin: CPU 620 MiB, GPU 3598 MiB
[11/26/2021-14:22:27] [I] [TRT] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 620, GPU 3598 (MiB)
[11/26/2021-14:22:27] [I] [TRT] [MemUsageChange] Init cuDNN: CPU +0, GPU +0, now: CPU 620, GPU 3598 (MiB)
[11/26/2021-14:22:27] [I] [TRT] [MemUsageSnapshot] ExecutionContext creation end: CPU 623 MiB, GPU 3603 MiB
[11/26/2021-14:22:27] [I] Created input binding for input_tensor:0 with dimensions 1x320x320x3
[11/26/2021-14:22:27] [I] Created output binding for num_detections with dimensions 1x1
[11/26/2021-14:22:27] [I] Created output binding for detection_boxes with dimensions 1x100x4
[11/26/2021-14:22:27] [I] Created output binding for detection_scores with dimensions 1x100
[11/26/2021-14:22:27] [I] Created output binding for detection_classes with dimensions 1x100
[11/26/2021-14:22:27] [I] Starting inference
[11/26/2021-14:22:28] [E] Error[2]: [pluginV2DynamicExtRunner.cpp::execute::115] Error Code 2: Internal Error (Assertion status == kSTATUS_SUCCESS failed.)
trtexec: samples/common/sampleInference.cpp:465: void sample::{anonymous}::Iteration::createEnqueueFunction(const sample::InferenceOptions&, nvinfer1::IExecutionContext&, sample::Bindings&): Assertion `ret' failed.
```

Do you maybe know what causes the issue? If this model is not supported by TensorRT do you maybe know exactly which models have been tested with this conversion workflow? (saved_model (tf2 OD) -> ONNX -> trt)

When I change the precision to FP16 I am not even able to build the engine and get a similar error:
 
```
[TensorRT] VERBOSE: >>>>>>>>>>>>>>> Chose Runner Type: Reformat Tactic: 0
[TensorRT] VERBOSE: *************** Autotuning format combination:  -> Float(51216,4,1) ***************
[TensorRT] VERBOSE: *************** Autotuning format combination:  -> Half(51216,4,1) ***************
[TensorRT] VERBOSE: *************** Autotuning Reformat:Float(51216,4,1) -> Half(51216,4,1) ***************
[TensorRT] VERBOSE: *************** Autotuning Reformat:Float(51216:32,4,1) -> Float(51216,4,1) ***************
[TensorRT] VERBOSE: *************** Autotuning Reformat:Float(51216:32,4,1) -> Half(51216,4,1) ***************
[TensorRT] VERBOSE: *************** Autotuning Reformat:Half(51216,4,1) -> Float(51216,4,1) ***************
[TensorRT] VERBOSE: *************** Autotuning Reformat:Half(51216:2,4,1) -> Float(51216,4,1) ***************
[TensorRT] VERBOSE: *************** Autotuning Reformat:Half(51216:2,4,1) -> Half(51216,4,1) ***************
[TensorRT] VERBOSE: *************** Autotuning Reformat:Float(12804,1,1) -> Half(12804,1,1) ***************
[TensorRT] VERBOSE: --------------- Timing Runner: Optimizer Reformat (Reformat)
[TensorRT] VERBOSE: Tactic: 1002 Time: 0.026666
[TensorRT] VERBOSE: Tactic: 0 Time: 0.019219
[TensorRT] VERBOSE: Fastest Tactic: 0 Time: 0.019219
[TensorRT] VERBOSE: *************** Autotuning Reformat:Half(12804,1,1) -> Float(12804,1,1) ***************
[TensorRT] VERBOSE: --------------- Timing Runner: Optimizer Reformat (Reformat)
[TensorRT] VERBOSE: Tactic: 1002 Time: 0.028438
[TensorRT] VERBOSE: Tactic: 0 Time: 0.015053
[TensorRT] VERBOSE: Fastest Tactic: 0 Time: 0.015053
[TensorRT] VERBOSE: *************** Autotuning Reformat:Float(51216,4,1) -> Half(51216,4,1) ***************
[TensorRT] VERBOSE: *************** Autotuning Reformat:Half(51216,4,1) -> Float(51216,4,1) ***************
[TensorRT] VERBOSE: *************** Autotuning format combination: Float(51216,4,1), Float(12804,1,1), Float(51216,4,1) -> Int32(1,1), Float(400,4,1), Float(100,1), Int32(100,1) ***************
[TensorRT] VERBOSE: --------------- Timing Runner: nms/non_maximum_suppression_first (PluginV2)
[TensorRT] VERBOSE: Deleting timing cache: 1043 entries, 1720 hits
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 903, GPU 3223 (MiB)
[TensorRT] ERROR: 2: [pluginV2DynamicExtRunner.cpp::execute::115] Error Code 2: Internal Error (Assertion status == kSTATUS_SUCCESS failed.)
Traceback (most recent call last):
  File "./TensorRT-support-for-Tensorflow-2-Object-Detection-Models/build_engine.py", line 240, in <module>
    main(args)
  File "./TensorRT-support-for-Tensorflow-2-Object-Detection-Models/build_engine.py", line 212, in main
    args.calib_batch_size)
  File "./TensorRT-support-for-Tensorflow-2-Object-Detection-Models/build_engine.py", line 203, in create_engine
    with self.builder.build_engine(self.network, self.config) as engine, open(engine_path, "wb") as f:
AttributeError: __enter__
```
It seems like it is related to this issue: https://github.com/NVIDIA/TensorRT/issues/1538

**Comment by mezdahun** [comment]
The problem seems to be that TensorRT 8.0.1 does not support EfficientNMS, but on JetPack4.6 (which is the most recent one as of now) for Jetson Nano this is the TensorRT version. Is there any possibility to solve this? None of the TF2OD models that I tried could be successfully built on the Nano with JetPack4.6 (TensorRT 8.0.1). Is there any possibility to use some fallback pluging for EfficientNMS?

**Comment by mezdahun** [comment]
https://forums.developer.nvidia.com/t/tf2od-on-jetson-nano-4gb-tf-onnx-trt-seemingly-not-supported-due-to-tensorrt-version/196389

**Comment by franferraz98** [comment]
Hi! Did you manage to solve this? I tried to use BatchedNMS but the error persists. Any other ideas?

**Comment by mezdahun** [comment]
> Hi! Did you manage to solve this? I tried to use BatchedNMS but the error persists. Any other ideas?

Hi, according to the nVidia developer's answer on my forum topic (link above) we will have to wait for JetPack 4.6.1 with new TensorRT version, otherwise using BatchedNMS plugin as fallback will increase the latency a lot. As this is not acceptable in our application we didn't try to make Mobilenetv2 work with this fallback. In case you succeed though, it looks like we are not alone with the problem, so sharing your answer would surely help on others for the time being.

**Comment by arifftrigon** [comment]
Hey, I'm having the same issue. Using SSD mobilenet v2 for custom OD training, I converted from pb -> ONNX but failed when attempting to convert to trt/parse into jetson nano trt. It will show 'Error[2]: [pluginV2DynamicExtRunner.cpp::execute::115] Error Code 2: Internal Error (Assertion status == kSTATUS_SUCCESS failed.)'. Still hangin around and clueless on how to solve this issue..so EfficientNMS_TRT will be supported in JetPack 4.6.1 release soon?

**Comment by pskiran1** [comment]
Hi,

We have [official repo](https://github.com/NVIDIA/TensorRT/tree/main/samples/python/tensorflow_object_detection_api) available now, please reach out here for the help.
This repo will be removed now and it was temporary.

Thank you.
