### ISSUE TITLE
PyCUDA error: initialization of _driver raised unreported exception

### ISSUE THREAD

**Issue by franferraz98** [pskiran1/TensorRT-support-for-Tensorflow-2-Object-Detection-Models#7]
Hi,

when I execute `python3 build_engine.py --onnx ../onnx_model/model.onnx --engine ../trt_engine/engine.trt --precision fp16` I get the following error: 
```

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "build_engine.py", line 24, in <module>
    import pycuda.driver as cuda
  File "/home/deeplearning/.local/lib/python3.8/site-packages/pycuda/driver.py", line 65, in <module>
    from pycuda._driver import *  # noqa
SystemError: initialization of _driver raised unreported exception
```

I've red on other forums that this may be an issue of my PyCUDA installation, so I tried to build from source, where I get:

```
x86_64-linux-gnu-g++ -pthread -shared -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.8/src/cpp/cuda.o build/temp.linux-x86_64-3.8/src/cpp/bitlog.o build/temp.linux-x86_64-3.8/src/wrapper/wrap_cudadrv.o build/temp.linux-x86_64-3.8/src/wrapper/mempool.o build/temp.linux-x86_64-3.8/src/wrapper/wrap_curand.o -L/usr/lib/stubs -L/usr/lib64/stubs -L/usr/lib/stubs -L/usr/lib64/stubs -lboost_python-py38 -lboost_thread -lcuda -lcurand -o build/lib.linux-x86_64-3.8/pycuda/_driver.cpython-38-x86_64-linux-gnu.so
/usr/bin/ld: cannot find -lboost_python-py38
collect2: error: ld returned 1 exit status
```

I'm using Ubuntu 20.04, CUDA 11.5, cudNN 8.2, a GTX 1050 for a laptop and the 495.29.05 NVIDIA driver. I have trained several Tensorflow models, so I know the CUDA/cudNN installation are working. Could you give me some directions on how to solve this? What versions of CUDA/Linux have you tested the library on?

Thanks in advance, the project seems promising.

**Comment by pskiran1** [comment]
Hi,

We have [official repo](https://github.com/NVIDIA/TensorRT/tree/main/samples/python/tensorflow_object_detection_api) available now, please reach out here for the help.
This repo will be removed now and it was temporary.

Thank you.
